# Site settings
title: Obi Laboratory
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Obi laboratory at Tokyo Institute of Technology. Research in medical images and security of social infrastructure.
baseurl: "/obi-lab-website" # the subpath of your site, e.g. /blog/
url: "https://foxelas.github.io/obi-lab-website/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
