# Site settings
title: Obi Laboratory
email: your-email@domain.com
description:
  en: Obi laboratory at Tokyo Institute of Technology. Research in medical images and security of social infrastructure.
  ja: 科学技術創成研究院 小尾高史研究室
baseurl: "/obi-lab-website"
url: "https://foxelas.github.io/obi-lab-website/"

university:
  en: Tokyo Institute of Technology
  ja: 東京工業大学

labname:
  en: Obi Laboratory
  ja: 小尾研究室

#Affiliations
fir:
  en: Laboratory for Future Interdisciplinary Research of Science and Technology (FIRST)
  ja: 未来産業技術研究所 (FIRST)

iir:
  en: Institute of Innovative Research (IIR)
  ja: 科学技術創成研究院 (IIR)

assist:
  en: Advanced Research Center for Social Information Science And Technology (ASSIST)
  ja: 社会情報流通基盤研究センター (ASSIST)

gsic:
  en: Global Scientific Information and Computing Center (GSIC)
  ja: 学術国際情報センター (GSIC)

department:
  en: Department of Information and Communications Engineering
  ja: 工学院情報通信系

ict:
  en: Information and Communications Engineering Course (Graduate Major)
  ja: 工学院情報通信系情報通信コース (大学院課程)

ictund:
  en: Information and Communications Engineering (Undergraduate Major)
  ja: 工学院情報通信系　(学士課程)

hcsb:
  en: Human-Centered Science and Biomedical Engineering (Graduate Major)
  ja: 工学院情報通信系ライフエンジニアリングコース (大学院課程)

asprof:
  en: Associate Professor
  ja: 准教授

spdprof:
  en: Special Directive professor
  ja: 特命教授

spprof:
  en: Specially Appointed Professor
  ja: 特任教授

spaprof:
  en: Specially Appointed Assistant Professor
  ja: 特任助教

spassocprof:
  en: Specially Appointed Associate Professor
  ja: 特任准教授

secretary:
  en: Secretary
  ja: 秘書

spresearcher:
  en: Specially Appointed Researcher
  ja: 特任研究員

spexpert:
  en: Specially Appointed Expert
  ja: 特任専門員

conresearcher:
  en: Contracted Researcher
  ja: 受託研究員

doctoral:
  en: Doctoral Student
  ja: 博士

wdoctoral:
  en: Working Doctoral Student
  ja: 博士（社会人）

master:
  en: Master's Student
  ja: 修士

bachelor:
  en: Bachelor's Student
  ja: 学部

jica:
  en: JICA Research Student
  ja: JICA研究生

lresearcher:
  en: MEXT Japanese Language Trainee
  ja: 国費日本語研修生

# Address
address:
  en: R2-60, Nagatsuta-cho 4259, Midori Ward, Yokohama, Kanagawa
  ja: 〒226-8503 神奈川県横浜市緑区長津田町4259 R2-60
mainroom:
  en: "Main office: Bldg. R2, Room 326"
  ja: "教員室： R2棟 326号室"
otherroom:
  en: "Staff offices: Bldg. R2, Rooms 223, 226, 327"
  ja: "学生室： R2棟 223,226,327号室"

#polyglot
languages: ["en", "ja"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: false
sass:
  sourcemap: never

# Build settings
markdown: kramdown
